server:
  port: 8000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/ecom-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

---
# ============ DOCKER PROFILE ============
spring:
  config:
    activate:
      on-profile: docker

  redis:
    host: redis        # ✅ container name
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecom-app   # ✅ container name

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans   # ✅ container name
